[project]
name = "tuananhtbbk1986.github.io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tuan-Anh Le", email = "tuananhtbbk@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
tuananhtbbk1986.github.io = "giaminhgist_github_io:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
